# Use a Node.js base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy only the application code (excluding node_modules)
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

# clean install
RUN npm ci

# Copy files
COPY . . 

# Expose the port your frontend service runs on
EXPOSE 8080

# update PATH
RUN export PATH=$PATH:./node_modules/.bin

# Define the command to start the frontend
CMD ["npm", "run", "serve"]
